### ISSUE TITLE
Add Geo-Search to Biz model and route

### ISSUE THREAD

**Issue by geoffsimons** [jmpaik/wheatlessinv2#35]
GET /api/biz?southwest=<lat,lng>&northeast=<lat,lng>

The model will need to include a field for geo-location, which will also need to be indexed on the schema. There is a pretty good example in the following SO article.

http://stackoverflow.com/questions/24856912/geospatial-box-query-mongoose-node-js-mongodb-returns-no-results

**Comment by bazacko** [comment]
PR #39
