### ISSUE TITLE
Post route

### ISSUE THREAD

**Issue by bhavyaab** [jmpaik/wheatlessinv2#45]
we need to set wrong token to be say 401- error status. # @geoffsimons

**Comment by bhavyaab** [comment]
Please take a look again. It should be 404 error or 401?

**Comment by geoffsimons** [comment]
I can't tell if this is currently a false positive, or if we fixed it. Let's review tomorrow to figure it out.

**Comment by bazacko** [comment]
We'll check all status codes as part of another issue.
